// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axrsqqqpkcuxafftahhw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cnNxcXFwa2N1eGFmZnRhaGh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NzcxMjQsImV4cCI6MjA2NjM1MzEyNH0.MsWIu3azEv4alaFD7l-p0FkqxK4WXII8lO8OhtYx980";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);